context:
  version: "3.1.14"

package:
  name: nodemon
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/nodemon/-/nodemon-${{ version }}.tgz
  sha256: 6f8851bd80d32526612f6dd6703b65603cef497944a7c081580ae49ce3a2f252

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nodemon --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Monitor for any changes in your node.js application and automatically restart the server - perfect for development
  homepage: https://github.com/remy/nodemon
  repository: https://github.com/remy/nodemon

extra:
  recipe-maintainers:
    - danielnachun
