context:
  version: 3.1.4

package:
  name: nodemon
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/nodemon/-/nodemon-${{ version }}.tgz
  sha256: 20ef56c97886dcfea1ad3d43d99cbd3865c7026a8102e2f368f23a59c23da658

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - nodemon --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Monitor for any changes in your node.js application and automatically restart the server - perfect for development
  homepage: https://github.com/remy/nodemon
  repository: https://github.com/remy/nodemon

extra:
  recipe-maintainers:
    - danielnachun
